### PR TITLE
Maintenance Update

### PR DESCRIPTION
**Pull request by milindgoel15**
Updated dark mode colors to google dark mode colors
updated versions
update to api level 29

(you can pick commits as per your choice or merge all xD)

### CODE REVIEW

**Comment by Jertlok** [comment]
Thanks for the PR, I will have to split your commit as I actually merged my q-xmas branch that had all the maintenance updates you made.
As for the color, I guess that would be wise -- I need to check how it looks! :D

**Comment by milindgoel15** [comment]
Sure
Also look the color for dialogs inside settings. I wasn't able to find proper attributes of it to change its color too.

**Comment by milindgoel15** [comment]
any update??

**Comment by milindgoel15** [comment]
Rip recordie too

**Pull request closed without merging**
